# Generated by Django 5.1.7 on 2025-04-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
    ]
