# Generated by Django 5.1.7 on 2025-04-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0002_distance_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
