# Generated by Django 5.1.7 on 2025-04-15 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0003_city_x_city_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('ACO', 'Ant Colony Optimization'), ('ABCO', 'Artificial Bee Colony Optimization')], max_length=4)),
                ('route', models.JSONField()),
                ('distance', models.FloatField()),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
